AWSTemplateFormatVersion: 2010-09-09
Description: Terraform remote state stack
Parameters:
  StateBucketNamePrefix:
    Description: Name prefix of the state bucket
    Type: String
    Default: YOUR-NAME-terraform-workshop-state-bucket

Resources:
  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StateBucketNamePrefix}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  StateBucket:
    Description: Name of the state bucket
    Value: !Ref StateBucket
